package dev.elide.seam.backend;

import dev.elide.seam.model.Seam.*;
import dev.elide.seam.model.Seam.Module;
import dev.elide.seam.serialize.SeamJson;
import dev.elide.seam.validate.Validator;
import java.util.*;

public final class CHeader implements Backend {
  public String filename(Module module) {
    return "seam.h";
  }

  public String generate(Module m) {
    String guard = m.name().toUpperCase(Locale.ROOT) + "_SEAM_H";
    var out =
        new StringBuilder(
            "/* Generated by svmgen. ABI: "
                + SeamJson.fingerprint(m)
                + " */\n#ifndef "
                + guard
                + "\n#define "
                + guard
                + "\n"
                + "#include <stdint.h>\n"
                + "#include <stddef.h>\n\n"
                + "#ifdef __cplusplus\n"
                + "#define SEAM_ASSERT static_assert\n"
                + "#define SEAM_ALIGNOF alignof\n"
                + "extern \"C\" {\n"
                + "#else\n"
                + "#define SEAM_ASSERT _Static_assert\n"
                + "#define SEAM_ALIGNOF _Alignof\n"
                + "#endif\n\n");
    out.append("#define ")
        .append(m.name().toUpperCase(Locale.ROOT))
        .append("_SEAM_ABI ")
        .append(SeamJson.quote(SeamJson.fingerprint(m)))
        .append('\n');
    out.append("SEAM_ASSERT(sizeof(void *) == 8, \"seam target requires 64-bit pointers\");\n\n");
    for (String name : m.opaqueTypes()) out.append("struct ").append(name).append(";\n");
    for (Struct s : m.structs()) {
      out.append("struct ").append(s.name()).append(" {\n");
      long offset = 0;
      int padding = 0;
      for (Field f : s.fields()) {
        if (f.offset() > offset)
          out.append("  uint8_t seamPadding")
              .append(padding++)
              .append('[')
              .append(f.offset() - offset)
              .append("];\n");
        out.append("  ").append(Types.c(f.type())).append(' ').append(f.name()).append(";\n");
        offset = f.offset() + Validator.size(f.type());
      }
      if (s.size() > offset)
        out.append("  uint8_t seamPadding")
            .append(padding)
            .append('[')
            .append(s.size() - offset)
            .append("];\n");
      out.append("};\nSEAM_ASSERT(sizeof(struct ")
          .append(s.name())
          .append(") == ")
          .append(s.size())
          .append(", \"struct size\");\n");
      out.append("SEAM_ASSERT(SEAM_ALIGNOF(struct ")
          .append(s.name())
          .append(") == ")
          .append(s.alignment())
          .append(", \"struct alignment\");\n");
      for (Field f : s.fields())
        out.append("SEAM_ASSERT(offsetof(struct ")
            .append(s.name())
            .append(", ")
            .append(f.name())
            .append(") == ")
            .append(f.offset())
            .append(", \"field offset\");\n");
    }
    for (Function f : m.functions()) {
      out.append("\n/* ")
          .append(f.direction())
          .append("; error=")
          .append(f.error())
          .append(" */\n");
      for (Parameter p : f.abiParameters())
        out.append("/* ")
            .append(p.name())
            .append(": nullable=")
            .append(p.nullable())
            .append(" ownership=")
            .append(p.ownership())
            .append(" access=")
            .append(p.access())
            .append(" */\n");
      out.append(Types.c(f.returns())).append(' ').append(f.symbol()).append('(');
      out.append(
          f.abiParameters().isEmpty()
              ? "void"
              : String.join(
                  ", ", f.abiParameters().stream().map(p -> Types.c(p) + " " + p.name()).toList()));
      out.append(");\n");
    }
    return out.append(
            "\n#ifdef __cplusplus\n}\n#endif\n#undef SEAM_ASSERT\n#undef SEAM_ALIGNOF\n#endif\n")
        .toString();
  }
}
