package dev.elide.seam.backend;

import dev.elide.seam.model.Seam.*;
import dev.elide.seam.model.Seam.Module;
import dev.elide.seam.serialize.SeamJson;
import java.util.*;

/** LLVM 23 declaration contracts. These do not provide native implementation bodies. */
public final class Llvm implements Backend {
  public String filename(Module module) {
    return "seam.ll";
  }

  public String generate(Module m) {
    var out =
        new StringBuilder(
            "; Generated by svmgen for LLVM 23. ABI: "
                + SeamJson.fingerprint(m)
                + "\n"
                + "; Apply these contracts to actual objects using svmgen apply before ThinLTO"
                + " indexing.\n"
                + "source_filename = \"seam-contracts\"\n");
    out.append("target triple = ").append(SeamJson.quote(m.targetTriple())).append("\n\n");
    for (Function f : m.functions()) {
      out.append("declare ")
          .append(Types.llvm(f.returns()))
          .append(" @")
          .append(f.symbol())
          .append('(');
      out.append(
              String.join(
                  ", ",
                  f.abiParameters().stream()
                      .map(
                          p -> {
                            String attributes = attributes(p.facts());
                            return Types.llvm(p.type())
                                + (attributes.isEmpty() ? "" : " " + attributes)
                                + " %"
                                + p.name();
                          })
                      .toList()))
          .append(')');
      String attrs = attributes(f.facts());
      if (!attrs.isEmpty()) out.append(' ').append(attrs);
      out.append('\n');
    }
    out.append("\n!svmgen.contract = !{!0}\n!0 = !{!\"")
        .append(SeamJson.fingerprint(m))
        .append("\"}\n");
    return out.toString();
  }

  private static String attributes(Map<String, Fact> facts) {
    var attrs = new ArrayList<String>();
    facts.forEach(
        (name, fact) -> {
          if (!fact.enabled() || !fact.approved() || name.equals("native_leaf")) return;
          attrs.add(
              switch (name) {
                case "nocapture" -> "captures(none)";
                case "align" -> "align " + fact.value();
                case "dereferenceable" -> "dereferenceable(" + fact.value() + ")";
                default -> name;
              });
        });
    return String.join(" ", attrs);
  }
}
