package dev.elide.seam.backend;

import dev.elide.seam.model.Seam.Function;
import dev.elide.seam.model.Seam.Module;

/**
 * Registers known FFM ABI shapes with Native Image before analysis; addresses stay runtime-bound.
 */
public final class NativeImageForeign implements Backend {
  public String filename() {
    return "SeamForeignFeature.java";
  }

  public String generate(Module module) {
    var out =
        new StringBuilder(
            """
            // Generated by svmgen. Enable only in Native Image applications using the FFM bindings.
            package dev.elide.seam.generated;

            import org.graalvm.nativeimage.hosted.Feature;
            import org.graalvm.nativeimage.hosted.RuntimeClassInitialization;
            import org.graalvm.nativeimage.hosted.RuntimeForeignAccess;

            public final class SeamForeignFeature implements Feature {
                @Override public void duringSetup(DuringSetupAccess access) {
            """);
    for (Function function : module.functions()) {
      out.append("        RuntimeForeignAccess.registerForDowncall(SeamFFM.")
          .append(function.name())
          .append("_DESCRIPTOR);\n");
      out.append(
              "       "
                  + " RuntimeClassInitialization.initializeAtRunTime(\"dev.elide.seam.generated.SeamFFM$")
          .append(function.name())
          .append("_Binding\");\n");
    }
    return out.append("    }\n}\n").toString();
  }
}
