package dev.elide.seam.backend;

import dev.elide.seam.model.Seam.Function;
import dev.elide.seam.model.Seam.Module;

/**
 * Registers known FFM ABI shapes with Native Image before analysis; addresses stay runtime-bound.
 */
public final class NativeImageForeign implements Backend {
  public String filename(Module module) {
    return module.foreignFeatureClass() + ".java";
  }

  public String generate(Module module) {
    String pkg = module.javaPackageName(), ffm = module.ffmClass();
    var out =
        new StringBuilder(
            "// Generated by svmgen. Enable only in Native Image applications using the FFM"
                + " bindings.\n"
                + "package "
                + pkg
                + ";\n\n"
                + "import org.graalvm.nativeimage.hosted.Feature;\n"
                + "import org.graalvm.nativeimage.hosted.RuntimeClassInitialization;\n"
                + "import org.graalvm.nativeimage.hosted.RuntimeForeignAccess;\n\n"
                + "public final class "
                + module.foreignFeatureClass()
                + " implements Feature {\n"
                + "    @Override public void duringSetup(DuringSetupAccess access) {\n");
    for (Function function : module.functions()) {
      out.append("        RuntimeForeignAccess.registerForDowncall(")
          .append(ffm)
          .append('.')
          .append(function.name())
          .append("_DESCRIPTOR);\n");
      out.append("        RuntimeClassInitialization.initializeAtRunTime(\"")
          .append(pkg)
          .append('.')
          .append(ffm)
          .append('$')
          .append(function.name())
          .append("_Binding\");\n");
    }
    return out.append("    }\n}\n").toString();
  }
}
