package dev.elide.seam.backend;

import dev.elide.seam.model.Seam.*;
import dev.elide.seam.model.Seam.Module;
import dev.elide.seam.serialize.SeamJson;
import java.util.*;

public final class NativeImage implements Backend {
  public String filename(Module module) {
    return module.nativeClass() + ".java";
  }

  private static boolean nativeLeaf(Function f) {
    Fact leaf = f.facts().get("native_leaf");
    return leaf != null && leaf.enabled() && leaf.approved();
  }

  private static String carrier(Parameter p) {
    return p.name().equals("isolate_thread") ? "IsolateThread" : Types.java(p.type());
  }

  private static boolean unsignedSmall(Type t) {
    return t == Scalar.U8 || t == Scalar.U16;
  }

  private static boolean small(Type t) {
    return t instanceof Scalar s && s != Scalar.VOID && s.bytes < 4;
  }

  /**
   * Native Image extends a narrow Java value by its Java (signed) type, so unsigned values leaving
   * Java travel as a zero-extended {@code int}; the C ABI reads the same low bits either way.
   */
  private static String widened(Type t, String value) {
    if (t == Scalar.U8) return value + " & 0xff";
    if (t == Scalar.U16) return value + " & 0xffff";
    if (t == Scalar.BOOL) return value + " ? 1 : 0";
    return value;
  }

  /** Only the imports a module uses, so checked-in output compiles cleanly under linters. */
  private static Set<String> imports(Module m) {
    var imports = new TreeSet<String>();
    for (Function f : m.functions()) {
      if (f.direction() == Direction.IMPORT) imports.add("org.graalvm.nativeimage.c.function.CFunction");
      else {
        imports.add("org.graalvm.nativeimage.IsolateThread");
        imports.add("org.graalvm.nativeimage.c.function.CEntryPoint");
        if (f.error() == ErrorConvention.NULL_SENTINEL) imports.add("org.graalvm.word.WordFactory");
      }
      var carriers = new ArrayList<String>();
      carriers.add(Types.java(f.returns()));
      f.parameters().forEach(p -> carriers.add(Types.java(p.type())));
      for (String c : carriers)
        if (c.equals("PointerBase")) imports.add("org.graalvm.word.PointerBase");
        else if (c.equals("VoidPointer") || c.startsWith("C"))
          imports.add("org.graalvm.nativeimage.c.type." + c);
    }
    return imports;
  }

  public String generate(Module m) {
    var out =
        new StringBuilder(
            "// Generated by svmgen. Unsigned integer carriers preserve their raw bits.\n"
                + "package "
                + m.javaPackageName()
                + ";\n\n");
    for (String i : imports(m)) out.append("import ").append(i).append(";\n");
    out.append("\npublic final class ")
        .append(m.nativeClass())
        .append(" {\n    private ")
        .append(m.nativeClass())
        .append("() {}\n");
    out.append("    public static final String ABI_FINGERPRINT = ")
        .append(SeamJson.quote(SeamJson.fingerprint(m)))
        .append(";\n");
    for (Function f : m.functions()) {
      boolean lowered =
          f.direction() == Direction.IMPORT && f.parameters().stream().anyMatch(p -> unsignedSmall(p.type()));
      if (lowered) {
        out.append("    public static ")
            .append(Types.java(f.returns()))
            .append(' ')
            .append(f.name())
            .append('(')
            .append(
                String.join(
                    ", ", f.parameters().stream().map(p -> carrier(p) + " " + p.name()).toList()))
            .append(") {\n        ")
            .append(f.returns() == Scalar.VOID ? "" : "return ")
            .append(f.name())
            .append("Native(")
            .append(
                String.join(
                    ", ",
                    f.parameters().stream()
                        .map(p -> unsignedSmall(p.type()) ? widened(p.type(), p.name()) : p.name())
                        .toList()))
            .append(");\n    }\n");
      }
      if (f.direction() == Direction.IMPORT)
        out.append("    @CFunction(value = ")
            .append(SeamJson.quote(f.symbol()))
            .append(nativeLeaf(f) ? ", transition = CFunction.Transition.NO_TRANSITION" : "")
            .append(lowered ? ")\n    private static native " : ")\n    public static native ");
      else
        out.append("    @CEntryPoint(name = ")
            .append(SeamJson.quote(f.symbol()))
            .append(f.include() == null ? "" : ", include = " + f.include() + ".class")
            .append(")\n    public static ");
      boolean widenReturn = f.direction() == Direction.EXPORT && small(f.returns());
      out.append(widenReturn ? "int" : Types.java(f.returns()))
          .append(' ')
          .append(f.name())
          .append(lowered ? "Native" : "")
          .append('(');
      out.append(
          String.join(
              ", ",
              f.abiParameters().stream()
                  .map(
                      p ->
                          (lowered && unsignedSmall(p.type()) ? "int" : carrier(p))
                              + " "
                              + p.name())
                  .toList()));
      if (f.direction() == Direction.IMPORT) {
        out.append(");\n");
        continue;
      }
      out.append(") {\n");
      boolean translate = f.error() != ErrorConvention.ABORT;
      if (translate) out.append("        try {\n");
      out.append(translate ? "            " : "        ");
      if (f.returns() != Scalar.VOID) out.append("return ");
      String call =
          f.javaTarget()
              + "("
              + String.join(", ", f.parameters().stream().map(Parameter::name).toList())
              + ")";
      out.append(widenReturn ? widened(f.returns(), call) : call).append(";\n");
      if (translate) {
        out.append("        } catch (Throwable failure) {\n            return ");
        if (f.error() == ErrorConvention.NULL_SENTINEL) out.append("WordFactory.nullPointer()");
        else {
          out.append(f.sentinel());
          if (f.returns() == Scalar.I64) out.append('L');
        }
        out.append(";\n        }\n");
      }
      out.append("    }\n");
    }
    return out.append("}\n").toString();
  }
}
