package dev.elide.seam.backend;

import dev.elide.seam.model.Seam.*;
import dev.elide.seam.model.Seam.Module;
import dev.elide.seam.serialize.SeamJson;
import java.util.*;

public final class NativeImage implements Backend {
  public String filename(Module module) {
    return module.nativeClass() + ".java";
  }

  private static boolean nativeLeaf(Function f) {
    Fact leaf = f.facts().get("native_leaf");
    return leaf != null && leaf.enabled() && leaf.approved();
  }

  private static String carrier(Parameter p) {
    return p.name().equals("isolate_thread") ? "IsolateThread" : Types.java(p.type());
  }

  /** Only the imports a module uses, so checked-in output compiles cleanly under linters. */
  private static Set<String> imports(Module m) {
    var imports = new TreeSet<String>();
    for (Function f : m.functions()) {
      if (f.direction() == Direction.IMPORT) imports.add("org.graalvm.nativeimage.c.function.CFunction");
      else {
        imports.add("org.graalvm.nativeimage.IsolateThread");
        imports.add("org.graalvm.nativeimage.c.function.CEntryPoint");
        if (f.error() == ErrorConvention.NULL_SENTINEL) imports.add("org.graalvm.word.WordFactory");
      }
      var carriers = new ArrayList<String>();
      carriers.add(Types.java(f.returns()));
      f.parameters().forEach(p -> carriers.add(Types.java(p.type())));
      for (String c : carriers)
        if (c.equals("PointerBase")) imports.add("org.graalvm.word.PointerBase");
        else if (c.equals("VoidPointer") || c.startsWith("C"))
          imports.add("org.graalvm.nativeimage.c.type." + c);
    }
    return imports;
  }

  public String generate(Module m) {
    var out =
        new StringBuilder(
            "// Generated by svmgen. Unsigned integer carriers preserve their raw bits.\n"
                + "package "
                + m.javaPackageName()
                + ";\n\n");
    for (String i : imports(m)) out.append("import ").append(i).append(";\n");
    out.append("\npublic final class ")
        .append(m.nativeClass())
        .append(" {\n    private ")
        .append(m.nativeClass())
        .append("() {}\n");
    out.append("    public static final String ABI_FINGERPRINT = ")
        .append(SeamJson.quote(SeamJson.fingerprint(m)))
        .append(";\n");
    for (Function f : m.functions()) {
      if (f.direction() == Direction.IMPORT)
        out.append("    @CFunction(value = ")
            .append(SeamJson.quote(f.symbol()))
            .append(nativeLeaf(f) ? ", transition = CFunction.Transition.NO_TRANSITION" : "")
            .append(")\n    public static native ");
      else
        out.append("    @CEntryPoint(name = ")
            .append(SeamJson.quote(f.symbol()))
            .append(f.include() == null ? "" : ", include = " + f.include() + ".class")
            .append(")\n    public static ");
      out.append(Types.java(f.returns())).append(' ').append(f.name()).append('(');
      out.append(
          String.join(
              ", ", f.abiParameters().stream().map(p -> carrier(p) + " " + p.name()).toList()));
      if (f.direction() == Direction.IMPORT) {
        out.append(");\n");
        continue;
      }
      out.append(") {\n");
      boolean translate = f.error() != ErrorConvention.ABORT;
      if (translate) out.append("        try {\n");
      out.append(translate ? "            " : "        ");
      if (f.returns() != Scalar.VOID) out.append("return ");
      out.append(f.javaTarget())
          .append('(')
          .append(String.join(", ", f.parameters().stream().map(Parameter::name).toList()))
          .append(");\n");
      if (translate) {
        out.append("        } catch (Throwable failure) {\n            return ");
        if (f.error() == ErrorConvention.NULL_SENTINEL) out.append("WordFactory.nullPointer()");
        else {
          out.append(f.sentinel());
          if (f.returns() == Scalar.I64) out.append('L');
        }
        out.append(";\n        }\n");
      }
      out.append("    }\n");
    }
    return out.append("}\n").toString();
  }
}
