package dev.elide.seam.backend;

import dev.elide.seam.model.Seam.*;
import dev.elide.seam.model.Seam.Module;
import dev.elide.seam.serialize.SeamJson;
import dev.elide.seam.validate.Validator;

public final class RustFfi implements Backend {
  public String filename(Module module) {
    return "seam.rs";
  }

  public String generate(Module m) {
    var out =
        new StringBuilder(
            "// Generated by svmgen. Raw ABI; callers uphold ownership and contracts.\n");
    out.append("pub const ABI_FINGERPRINT: &str = ")
        .append(SeamJson.quote(SeamJson.fingerprint(m)))
        .append(";\n");
    out.append("const _: () = assert!(core::mem::size_of::<*const ()>() == 8);\n");
    for (String name : m.opaqueTypes())
      out.append("#[repr(C)]\npub struct ").append(name).append(" { _private: [u8; 0] }\n");
    for (Signature c : m.callbacks()) {
      out.append("pub type ")
          .append(c.name())
          .append(" = Option<unsafe extern \"C\" fn(")
          .append(String.join(", ", c.parameters().stream().map(Types::rust).toList()))
          .append(')');
      if (c.returns() != Scalar.VOID) out.append(" -> ").append(Types.rust(c.returns()));
      out.append(">;\n");
    }
    for (Struct s : m.structs()) {
      out.append("#[repr(C)]\npub struct ").append(s.name()).append(" {\n");
      long offset = 0;
      int padding = 0;
      for (Field f : s.fields()) {
        if (f.offset() > offset)
          out.append("    pub seamPadding")
              .append(padding++)
              .append(": [u8; ")
              .append(f.offset() - offset)
              .append("],\n");
        out.append("    pub ")
            .append(f.name())
            .append(": ")
            .append(Types.rust(f.type()))
            .append(",\n");
        offset = f.offset() + Validator.size(f.type());
      }
      if (s.size() > offset)
        out.append("    pub seamPadding")
            .append(padding)
            .append(": [u8; ")
            .append(s.size() - offset)
            .append("],\n");
      out.append("}\nconst _: () = {\n    assert!(core::mem::size_of::<")
          .append(s.name())
          .append(">() == ")
          .append(s.size())
          .append(");\n");
      out.append("    assert!(core::mem::align_of::<")
          .append(s.name())
          .append(">() == ")
          .append(s.alignment())
          .append(");\n");
      for (Field f : s.fields())
        out.append("    assert!(core::mem::offset_of!(")
            .append(s.name())
            .append(", ")
            .append(f.name())
            .append(") == ")
            .append(f.offset())
            .append(");\n");
      out.append("};\n");
    }
    out.append("\nunsafe extern \"C\" {\n");
    for (Function f : m.functions()) {
      out.append("    // ").append(f.direction()).append("; error=").append(f.error()).append('\n');
      for (Parameter p : f.abiParameters())
        out.append("    // ")
            .append(p.name())
            .append(": nullable=")
            .append(p.nullable())
            .append(" ownership=")
            .append(p.ownership())
            .append(" access=")
            .append(p.access())
            .append('\n');
      out.append("    #[link_name = ")
          .append(SeamJson.quote(f.symbol()))
          .append("]\n    pub fn ")
          .append(f.name())
          .append('(');
      out.append(
              String.join(
                  ", ",
                  f.abiParameters().stream().map(p -> p.name() + ": " + Types.rust(p)).toList()))
          .append(')');
      if (f.returns() != Scalar.VOID) out.append(" -> ").append(Types.rust(f.returns()));
      out.append(";\n");
    }
    out.append("}\n");
    // Function-pointer types for callers that resolve symbols dynamically (dlsym/GetProcAddress).
    for (Function f : m.functions()) {
      out.append("pub type ")
          .append(Character.toUpperCase(f.name().charAt(0)))
          .append(f.name().substring(1))
          .append("Fn = unsafe extern \"C\" fn(")
          .append(String.join(", ", f.abiParameters().stream().map(Types::rust).toList()))
          .append(')');
      if (f.returns() != Scalar.VOID) out.append(" -> ").append(Types.rust(f.returns()));
      out.append(";\n");
    }
    var imports = m.functions().stream().filter(f -> f.direction() == Direction.IMPORT).toList();
    if (!imports.isEmpty()) {
      out.append(
          "\n/// Pins each import's implementation, in scope under its symbol name, to this ABI.\n"
              + "#[allow(unused_macros)]\nmacro_rules! assert_implementations {\n"
              + "    () => {\n        const _: () = {\n");
      for (Function f : imports) {
        out.append("            let _: unsafe extern \"C\" fn(")
            .append(
                String.join(", ", f.abiParameters().stream().map(Types::rust).toList()))
            .append(')');
        if (f.returns() != Scalar.VOID) out.append(" -> ").append(Types.rust(f.returns()));
        out.append(" = ").append(f.symbol()).append(";\n");
      }
      out.append(
          "        };\n    };\n}\n#[allow(unused_imports)]\npub(crate) use assert_implementations;\n");
    }
    return out.toString();
  }
}
