package dev.elide.myna.backend;

import dev.elide.myna.model.Seam.*;
import dev.elide.myna.model.Seam.Module;
import dev.elide.myna.serialize.SeamJson;
import dev.elide.myna.validate.Validator;
import java.util.*;

public final class JavaFfm implements Backend {
  public String filename(Module module) {
    return module.ffmClass() + ".java";
  }

  public String generate(Module m) {
    var out =
        new StringBuilder(
            "// Generated by myna; Java 25 FFM.\n"
                + "package "
                + m.javaPackageName()
                + ";\n\n"
                + "import java.lang.foreign.*;\n"
                + "import java.lang.invoke.MethodHandle;\n\n"
                + "public final class "
                + m.ffmClass()
                + " {\n"
                + "    private "
                + m.ffmClass()
                + "() {}\n");
    out.append("    public static final String ABI_FINGERPRINT = ")
        .append(SeamJson.quote(SeamJson.fingerprint(m)))
        .append(";\n");
    out.append(
        "    static {\n"
            + "        if (ValueLayout.ADDRESS.byteSize() != 8) throw new"
            + " ExceptionInInitializerError(\"64-bit seam target required\");\n"
            + "    }\n");
    for (Struct s : m.structs()) {
      var elements = new ArrayList<String>();
      long offset = 0;
      for (Field f : s.fields()) {
        if (f.offset() > offset)
          elements.add("MemoryLayout.paddingLayout(" + (f.offset() - offset) + ")");
        elements.add(Types.layout(f.type()) + ".withName(\"" + f.name() + "\")");
        offset = f.offset() + Validator.size(f.type());
      }
      if (s.size() > offset)
        elements.add("MemoryLayout.paddingLayout(" + (s.size() - offset) + ")");
      out.append("    public static final StructLayout ")
          .append(s.name())
          .append("_LAYOUT = MemoryLayout.structLayout(\n        ")
          .append(String.join(",\n        ", elements))
          .append(");\n");
      for (Field f : s.fields())
        out.append("    public static final long ")
            .append(s.name())
            .append('_')
            .append(f.name())
            .append("_OFFSET = ")
            .append(f.offset())
            .append("L;\n");
    }
    for (Function f : m.functions().stream().map(d -> ffmForm(m, d)).toList()) {
      var args = new ArrayList<String>();
      if (f.returns() != Scalar.VOID) args.add(Types.layout(f.returns()));
      f.abiParameters().forEach(p -> args.add(Types.layout(p.type())));
      out.append("    public static final FunctionDescriptor ")
          .append(f.name())
          .append("_DESCRIPTOR = FunctionDescriptor.")
          .append(f.returns() == Scalar.VOID ? "ofVoid(" : "of(")
          .append(String.join(", ", args))
          .append(");\n");
      out.append("    public static MethodHandle ")
          .append(f.name())
          .append(
              "(SymbolLookup lookup) {\n"
                  + "        return Linker.nativeLinker().downcallHandle(lookup.find(")
          .append(SeamJson.quote(f.symbol()))
          .append(").orElseThrow(() -> new UnsatisfiedLinkError(")
          .append(SeamJson.quote(f.symbol()))
          .append(")), ")
          .append(f.name())
          .append("_DESCRIPTOR);\n    }\n");
    }
    for (Function f : m.functions().stream().map(d -> ffmForm(m, d)).toList()) {
      String carrier = Types.ffmCarrier(f.returns());
      out.append(
              "    // Load the library in this class loader before first use. One handle per"
                  + " symbol.\n")
          .append("    private static final class ")
          .append(f.name())
          .append("_Binding {\n")
          .append("        static final MethodHandle HANDLE = ")
          .append(m.ffmClass())
          .append('.')
          .append(f.name())
          .append("(SymbolLookup.loaderLookup());\n    }\n")
          .append("    public static ")
          .append(carrier)
          .append(' ')
          .append(f.name())
          .append('(')
          .append(f.returns() instanceof Named ? "SegmentAllocator allocator" + (f.abiParameters().isEmpty() ? "" : ", ") : "")
          .append(
              String.join(
                  ", ",
                  f.abiParameters().stream()
                      .map(p -> Types.ffmCarrier(p.type()) + " " + p.name())
                      .toList()))
          .append(") throws Throwable {\n        ");
      if (f.returns() != Scalar.VOID) out.append("return (").append(carrier).append(") ");
      out.append(m.ffmClass())
          .append('.')
          .append(f.name())
          .append("_Binding.HANDLE.invokeExact(")
          .append(f.returns() instanceof Named ? "allocator" + (f.abiParameters().isEmpty() ? "" : ", ") : "")
          .append(String.join(", ", f.abiParameters().stream().map(Parameter::name).toList()))
          .append(");\n    }\n");
    }
    return out.append("}\n").toString();
  }

  /**
   * FFM passes records by value natively, so only exports (which Native Image publishes in
   * reference form) are lowered.
   */
  private static Function ffmForm(Module m, Function f) {
    return f.direction() == Direction.EXPORT ? ByValue.lower(m, f) : f;
  }
}
