package dev.elide.myna.backend;

import dev.elide.myna.model.Seam.*;
import dev.elide.myna.model.Seam.Module;
import dev.elide.myna.serialize.SeamJson;
import java.util.*;

/** LLVM 23 declaration contracts. These do not provide native implementation bodies. */
public final class Llvm implements Backend {
  public String filename(Module module) {
    return "seam.ll";
  }

  public String generate(Module m) {
    var out =
        new StringBuilder(
            "; Generated by myna for LLVM 23. ABI: "
                + SeamJson.fingerprint(m)
                + "\n"
                + "; Apply these contracts to actual objects using myna apply before ThinLTO"
                + " indexing.\n"
                + "source_filename = \"seam-contracts\"\n");
    out.append("target triple = ").append(SeamJson.quote(m.targetTriple())).append("\n\n");
    // By-value lowering is target-specific (registers, byval, sret), so a record-passing function
    // is declared only in its reference form; its by-value symbol could never match compiler output.
    for (Function f : m.functions()) declaration(m, ByValue.lower(m, f), out);
    out.append("\n!myna.contract = !{!0}\n!0 = !{!\"")
        .append(SeamJson.fingerprint(m))
        .append("\"}\n");
    return out.toString();
  }

  private static void declaration(Module m, Function f, StringBuilder out) {
    out.append("declare ")
        .append(Types.llvm(f.returns()))
        .append(" @")
        .append(f.symbol())
        .append('(');
    out.append(
            String.join(
                ", ",
                f.abiParameters().stream()
                    .map(
                        p -> {
                          String attributes =
                              String.join(
                                      " ",
                                      Types.extension(p.type(), m.targetTriple()),
                                      attributes(p.facts()))
                                  .strip();
                          return Types.llvm(p.type())
                              + (attributes.isEmpty() ? "" : " " + attributes)
                              + " %"
                              + p.name();
                        })
                    .toList()))
        .append(')');
    String attrs = attributes(f.facts());
    if (!attrs.isEmpty()) out.append(' ').append(attrs);
    out.append('\n');
  }

  private static String attributes(Map<String, Fact> facts) {
    var attrs = new ArrayList<String>();
    facts.forEach(
        (name, fact) -> {
          if (!fact.enabled() || !fact.approved() || name.equals("native_leaf")) return;
          attrs.add(
              switch (name) {
                case "nocapture" -> "captures(none)";
                case "align" -> "align " + fact.value();
                case "dereferenceable" -> "dereferenceable(" + fact.value() + ")";
                default -> name;
              });
        });
    return String.join(" ", attrs);
  }
}
