package dev.elide.myna.backend;

import dev.elide.myna.model.Seam.*;
import dev.elide.myna.model.Seam.Module;
import java.util.*;

/**
 * Consumer-owned SVM lifecycle integration; no prescribed GC registration or disposal mechanism.
 */
public final class NativeOwnership implements Backend {
  public String filename(Module m) {
    return m.ownershipClass() + ".java";
  }

  public String generate(Module m) {
    var out =
        new StringBuilder(
            "// Generated by myna. Lifecycle implementations are supplied by the consumer.\n"
                + "package "
                + m.javaPackageName()
                + ";\n\npublic final class "
                + m.ownershipClass()
                + " {\n    private "
                + m.ownershipClass()
                + "() {}\n");
    if (!m.resources().isEmpty())
      out.append(
"""
        /** Called exactly once by the consumer when its resource is no longer accessible. */
        @FunctionalInterface
        public interface NativeDestructor { void destroy(long address); }

        /**
         * Takes sole ownership on successful return. On exception, ownership stays with the generator.
         * Must return a non-null owner. Failed adoption must undo registrations without freeing address.
         * The consumer manages GC registration, access guards, and exactly-once destruction.
         * requiredThread is null for shared resources; otherwise access AND destruction require it.
         */
        @FunctionalInterface
        public interface ResourceFactory<T> {
            T adopt(long address, NativeDestructor destructor, java.lang.Thread requiredThread);
        }

""");
    for (Resource r : m.resources()) {
      Function create =
          m.functions().stream().filter(f -> f.name().equals(r.create())).findFirst().orElseThrow();
      var params = new ArrayList<String>();
      var args = new ArrayList<String>();
      for (int i = 0; i < create.parameters().size(); i++) {
        params.add(Types.java(create.parameters().get(i).type()) + " arg" + i);
        args.add("arg" + i);
      }
      out.append("    public static final class ")
          .append(r.name())
          .append(" {\n        private ")
          .append(r.name())
          .append("() {}\n")
          .append("        private static final NativeDestructor DESTRUCTOR = address -> ")
          .append(m.nativeClass())
          .append('.')
          .append(r.destroy())
          .append("(org.graalvm.word.WordFactory.pointer(address));\n")
          .append("        /** Null means native creation failed; the consumer is not called. */\n")
          .append("        public static <T> T create(ResourceFactory<T> factory")
          .append(params.isEmpty() ? "" : ", " + String.join(", ", params))
          .append(") {\n")
          .append("            java.util.Objects.requireNonNull(factory);\n")
          .append("            long address = ")
          .append(m.nativeClass())
          .append('.')
          .append(r.create())
          .append('(')
          .append(String.join(", ", args))
          .append(").rawValue();\n")
          .append("            if (address == 0) return null;\n")
          .append("            return adoptUnsafe(address, factory);\n        }\n")
          .append(
              "        /** Transfer sole ownership of a live allocation with no outstanding"
                  + " borrows. */\n")
          .append(
              "        public static <T> T adoptUnsafe(long address, ResourceFactory<T> factory)"
                  + " {\n")
          .append("            java.util.Objects.requireNonNull(factory);\n")
          .append(
              "            if (address == 0) throw new IllegalArgumentException(\"null"
                  + " resource\");\n")
          .append(
              "            try {\n"
                  + "                return java.util.Objects.requireNonNull(factory.adopt(address,"
                  + " DESTRUCTOR, ")
          .append(r.shared() ? "null" : "java.lang.Thread.currentThread()")
          .append(
              "));\n"
                  + "            } catch (RuntimeException | Error failure) {\n"
                  + "                DESTRUCTOR.destroy(address);\n"
                  + "                throw failure;\n"
                  + "            }\n"
                  + "        }\n"
                  + "    }\n");
    }
    if (!m.borrows().isEmpty())
      out.append(
"""
        /**
         * Consumer-owned off-heap bytes. A successful acquire keeps address/size stable and live
         * until release; writable access must be exclusive, read access must prevent mutation.
         * acquire may throw without acquiring; release must not throw. Views may share an owner.
         * A consumer with an externally guaranteed lifetime may implement these hooks as no-ops.
         */
        public interface NativeBuffer {
            void acquire(boolean writable);
            long address();
            long byteSize();
            void release(boolean writable);
        }

""");
    for (BufferBorrow b : m.borrows()) {
      Function f =
          m.functions().stream()
              .filter(x -> x.name().equals(b.function()))
              .findFirst()
              .orElseThrow();
      Parameter buffer =
          f.parameters().stream()
              .filter(p -> p.name().equals(b.parameter()))
              .findFirst()
              .orElseThrow();
      boolean writable = buffer.access() == Access.READ_WRITE;
      Type lengthType =
          f.parameters().stream()
              .filter(p -> p.name().equals(b.length()))
              .findFirst()
              .orElseThrow()
              .type();
      boolean narrow = lengthType == Scalar.I32 || lengthType == Scalar.U32;
      String maxLength = lengthType == Scalar.I32 ? "2147483647L" : "4294967295L";
      // Use positional generated names to avoid collisions with consumer parameter names.
      var nativeParams = new ArrayList<String>();
      var arrayParams = new ArrayList<String>();
      var call = new ArrayList<String>();
      int index = 0;
      String bufferName = "";
      for (Parameter p : f.parameters()) {
        String name = "arg" + index++;
        if (p == buffer) {
          bufferName = name;
          nativeParams.add("NativeBuffer " + name);
          arrayParams.add("byte[] " + name);
          call.add("pointer");
        } else if (p.name().equals(b.length())) call.add(narrow ? "(int) length" : "length");
        else {
          nativeParams.add(Types.java(p.type()) + " " + name);
          arrayParams.add(Types.java(p.type()) + " " + name);
          call.add(name);
        }
      }
      String invoke =
          (f.returns() == Scalar.VOID ? "" : "return ")
              + m.nativeClass()
              + "."
              + f.name()
              + "("
              + String.join(", ", call)
              + ");";
      out.append("    public static ")
          .append(Types.java(f.returns()))
          .append(' ')
          .append(f.name())
          .append('(')
          .append(String.join(", ", nativeParams))
          .append(") {\n")
          .append("        ")
          .append(bufferName)
          .append(".acquire(")
          .append(writable)
          .append(");\n        try {\n")
          .append("            long length = ")
          .append(bufferName)
          .append(".byteSize();\n")
          .append(
              narrow
                  ? "            if (length > "
                      + maxLength
                      + ") throw new IllegalArgumentException(\"buffer length exceeds ABI"
                      + " range\");\n"
                  : "")
          .append("            long address = ")
          .append(bufferName)
          .append(".address();\n")
          .append(
              "            if (length < 0 || (address == 0 && length != 0)) throw new"
                  + " IllegalArgumentException(\"invalid buffer extent\");\n")
          .append(
              "            org.graalvm.nativeimage.c.type.CCharPointer pointer = address == 0\n")
          .append(
              "                ? org.graalvm.nativeimage.StackValue.get(1) :"
                  + " org.graalvm.word.WordFactory.pointer(address);\n")
          .append("            ")
          .append(invoke)
          .append("\n        } finally {\n            ")
          .append(bufferName)
          .append(".release(")
          .append(writable)
          .append(");\n")
          .append("            java.lang.ref.Reference.reachabilityFence(")
          .append(bufferName)
          .append(");\n        }\n    }\n");
      out.append(
              "    /** Array convenience path; caller prevents conflicting concurrent array access."
                  + " */\n")
          .append("    public static ")
          .append(Types.java(f.returns()))
          .append(' ')
          .append(f.name())
          .append('(')
          .append(String.join(", ", arrayParams))
          .append(") {\n")
          .append("        long length = ")
          .append(bufferName)
          .append(".length;\n")
          .append(
              "        if (length == 0) {\n"
                  + "            org.graalvm.nativeimage.c.type.CCharPointer pointer ="
                  + " org.graalvm.nativeimage.StackValue.get(1);\n"
                  + "            ")
          .append(invoke)
          .append(f.returns() == Scalar.VOID ? "\n            return;" : "")
          .append("\n        }\n")
          .append(
              "        try (org.graalvm.nativeimage.PinnedObject pin ="
                  + " org.graalvm.nativeimage.PinnedObject.create(")
          .append(bufferName)
          .append(")) {\n")
          .append(
              "            org.graalvm.nativeimage.c.type.CCharPointer pointer ="
                  + " pin.addressOfArrayElement(0);\n"
                  + "            ")
          .append(invoke)
          .append("\n        }\n    }\n");
    }
    return out.append("}\n").toString();
  }
}
