// Generated by myna. Enable only in Native Image applications using the FFM bindings.
package dev.elide.myna.generated;

import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeClassInitialization;
import org.graalvm.nativeimage.hosted.RuntimeForeignAccess;

public final class MynaForeignFeature implements Feature {
    @Override public void duringSetup(DuringSetupAccess access) {
        RuntimeForeignAccess.registerForDowncall(MynaFFM.classify_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$classify_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.echo_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$echo_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.exercise_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$exercise_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.forEach_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$forEach_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.inspect_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$inspect_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.isHigh_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$isHigh_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.lowSigned_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$lowSigned_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.lowUnsigned_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$lowUnsigned_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.reducer_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$reducer_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.rotate_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$rotate_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.scale_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$scale_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.spread_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$spread_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.structProbe_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$structProbe_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.sum_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$sum_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.swapPair_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$swapPair_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.visit_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$visit_Binding");
        RuntimeForeignAccess.registerForDowncall(MynaFFM.widen_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.myna.generated.MynaFFM$widen_Binding");
    }
}
