// Generated by myna. Unsigned integer carriers preserve their raw bits.
package dev.elide.myna.generated;

import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.function.CEntryPointLiteral;
import org.graalvm.nativeimage.c.function.CFunction;
import org.graalvm.nativeimage.c.function.CFunctionPointer;
import org.graalvm.nativeimage.c.function.InvokeCFunctionPointer;
import org.graalvm.nativeimage.c.type.CCharPointer;
import org.graalvm.nativeimage.c.type.CConst;
import org.graalvm.nativeimage.c.type.CLongPointer;
import org.graalvm.word.Pointer;
import org.graalvm.word.PointerBase;

public final class MynaNative {
    private MynaNative() {}
    public static final String ABI_FINGERPRINT = "d44ec22d7c3a435496ea647adde107ba12093ac69cc1cb1fb165a07ff5292436";
    public static final class BufferView {
        private BufferView() {}
        public static final int SIZE = 24;
        public static final int ALIGNMENT = 8;
        public static CCharPointer data(PointerBase record) {
            return ((Pointer) record).readWord(0);
        }
        public static void data(PointerBase record, CCharPointer value) {
            ((Pointer) record).writeWord(0, value);
        }
        public static long length(PointerBase record) {
            return ((Pointer) record).readLong(8);
        }
        public static void length(PointerBase record, long value) {
            ((Pointer) record).writeLong(8, value);
        }
        public static int flags(PointerBase record) {
            return ((Pointer) record).readInt(16);
        }
        public static void flags(PointerBase record, int value) {
            ((Pointer) record).writeInt(16, value);
        }
    }
    public static final class Pair {
        private Pair() {}
        public static final int SIZE = 16;
        public static final int ALIGNMENT = 8;
        public static long left(PointerBase record) {
            return ((Pointer) record).readLong(0);
        }
        public static void left(PointerBase record, long value) {
            ((Pointer) record).writeLong(0, value);
        }
        public static int right(PointerBase record) {
            return ((Pointer) record).readInt(8);
        }
        public static void right(PointerBase record, int value) {
            ((Pointer) record).writeInt(8, value);
        }
    }
    public static final class Triple {
        private Triple() {}
        public static final int SIZE = 24;
        public static final int ALIGNMENT = 8;
        public static long a(PointerBase record) {
            return ((Pointer) record).readLong(0);
        }
        public static void a(PointerBase record, long value) {
            ((Pointer) record).writeLong(0, value);
        }
        public static long b(PointerBase record) {
            return ((Pointer) record).readLong(8);
        }
        public static void b(PointerBase record, long value) {
            ((Pointer) record).writeLong(8, value);
        }
        public static long c(PointerBase record) {
            return ((Pointer) record).readLong(16);
        }
        public static void c(PointerBase record, long value) {
            ((Pointer) record).writeLong(16, value);
        }
    }
    public interface Reducer extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long left, long right);
    }
    public interface Visitor extends CFunctionPointer {
        @InvokeCFunctionPointer
        int invoke(IsolateThread isolate, long value);
    }
    /** Entry-point addresses; CEntryPointLiteral.create is hosted-only, so initialize this class at image build time. */
    public static final class Literals {
        private Literals() {}
        public static final CEntryPointLiteral<Visitor> visit =
            CEntryPointLiteral.create(MynaNative.class, "visit", IsolateThread.class, long.class);
    }
    @CEntryPoint(name = "seam_classify")
    public static int classify(IsolateThread isolate_thread, short value, boolean strict) {
        return fixture.BufferOps.classify(value, strict);
    }
    @CEntryPoint(name = "seam_echo")
    public static int echo(IsolateThread isolate_thread, byte value) {
        return fixture.BufferOps.echo(value) & 0xff;
    }
    @CEntryPoint(name = "seam_exercise")
    public static long exercise(IsolateThread isolate_thread) {
        return fixture.BufferOps.exercise();
    }
    @CFunction(value = "seam_for_each")
    public static native int forEach(Visitor visitor, IsolateThread isolate, long count);
    @CFunction(value = "seam_inspect", transition = CFunction.Transition.NO_TRANSITION)
    public static native long inspect(CLongPointer value);
    @CEntryPoint(name = "seam_is_high")
    public static int isHigh(IsolateThread isolate_thread, byte value) {
        return fixture.BufferOps.isHigh(value) ? 1 : 0;
    }
    @CFunction(value = "seam_low_signed", transition = CFunction.Transition.NO_TRANSITION)
    public static native byte lowSigned(int value);
    @CFunction(value = "seam_low_unsigned", transition = CFunction.Transition.NO_TRANSITION)
    public static native byte lowUnsigned(int value);
    @CFunction(value = "seam_reducer")
    public static native Reducer reducer();
    @CFunction(value = "seam_rotate_myna_ref")
    public static native void rotate(PointerBase value, int times, PointerBase result);
    @CEntryPoint(name = "seam_scale_myna_ref")
    public static void scale(IsolateThread isolate_thread, @CConst PointerBase value, int factor, PointerBase result) {
        fixture.BufferOps.scale(value, factor, result);
    }
    @CEntryPoint(name = "seam_spread_myna_ref")
    public static void spread(IsolateThread isolate_thread, @CConst PointerBase value, PointerBase result) {
        fixture.BufferOps.spread(value, result);
    }
    @CEntryPoint(name = "seam_struct_probe")
    public static int structProbe(IsolateThread isolate_thread) {
        return fixture.BufferOps.structProbe();
    }
    @CEntryPoint(name = "seam_sum")
    public static long sum(IsolateThread isolate_thread, @CConst CCharPointer data, long length) {
        try {
            return fixture.BufferOps.sum(data, length);
        } catch (Throwable failure) {
            return -1L;
        }
    }
    @CFunction(value = "seam_swap_pair_myna_ref")
    public static native void swapPair(PointerBase value, PointerBase result);
    @CEntryPoint(name = "seam_visit")
    public static int visit(IsolateThread isolate_thread, long value) {
        return fixture.BufferOps.visit(value);
    }
    public static int widen(byte signedByte, byte unsignedByte, short signedShort, short unsignedShort, boolean flag) {
        return widenNative(signedByte, unsignedByte & 0xff, signedShort, unsignedShort & 0xffff, flag);
    }
    @CFunction(value = "seam_widen", transition = CFunction.Transition.NO_TRANSITION)
    private static native int widenNative(byte signedByte, int unsignedByte, short signedShort, int unsignedShort, boolean flag);
}
