// Generated by svmgen. Enable only in Native Image applications using the FFM bindings.
package dev.elide.seam.generated;

import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeClassInitialization;
import org.graalvm.nativeimage.hosted.RuntimeForeignAccess;

public final class SeamForeignFeature implements Feature {
    @Override public void duringSetup(DuringSetupAccess access) {
        RuntimeForeignAccess.registerForDowncall(SeamFFM.inspect_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$inspect_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.sum_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$sum_Binding");
    }
}
