// Generated by svmgen. Raw ABI; callers uphold ownership and contracts.
pub const ABI_FINGERPRINT: &str = "8a92ad19a5b593ca7a44354722924acef6f9c93e26bfbe9a55005c04cad53583";
const _: () = assert!(core::mem::size_of::<*const ()>() == 8);
#[repr(C)]
pub struct Buffer { _private: [u8; 0] }
#[repr(C)]
pub struct BufferView {
    pub data: *mut u8,
    pub length: u64,
    pub flags: u32,
    pub seamPadding0: [u8; 4],
}
const _: () = {
    assert!(core::mem::size_of::<BufferView>() == 24);
    assert!(core::mem::align_of::<BufferView>() == 8);
    assert!(core::mem::offset_of!(BufferView, data) == 0);
    assert!(core::mem::offset_of!(BufferView, length) == 8);
    assert!(core::mem::offset_of!(BufferView, flags) == 16);
};

unsafe extern "C" {
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // strict: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_classify"]
    pub fn classify(isolate_thread: *mut core::ffi::c_void, value: i16, strict: bool) -> i8;
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_echo"]
    pub fn echo(isolate_thread: *mut core::ffi::c_void, value: u8) -> u8;
    // IMPORT; error=NO_FAILURE
    // value: nullable=false ownership=BORROWED access=READ
    #[link_name = "seam_inspect"]
    pub fn inspect(value: *const i64) -> i64;
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_is_high"]
    pub fn isHigh(isolate_thread: *mut core::ffi::c_void, value: u8) -> bool;
    // IMPORT; error=NO_FAILURE
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_low_signed"]
    pub fn lowSigned(value: i32) -> i8;
    // IMPORT; error=NO_FAILURE
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_low_unsigned"]
    pub fn lowUnsigned(value: i32) -> u8;
    // EXPORT; error=INTEGER_SENTINEL
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // data: nullable=false ownership=BORROWED access=READ
    // length: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_sum"]
    pub fn sum(isolate_thread: *mut core::ffi::c_void, data: *const u8, length: i64) -> i64;
    // IMPORT; error=NO_FAILURE
    // signedByte: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // unsignedByte: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // signedShort: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // unsignedShort: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // flag: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_widen"]
    pub fn widen(signedByte: i8, unsignedByte: u8, signedShort: i16, unsignedShort: u16, flag: bool) -> i32;
}

/// Pins each import's implementation, in scope under its symbol name, to this ABI.
#[allow(unused_macros)]
macro_rules! assert_implementations {
    () => {
        const _: () = {
            let _: unsafe extern "C" fn(*const i64) -> i64 = seam_inspect;
            let _: unsafe extern "C" fn(i32) -> i8 = seam_low_signed;
            let _: unsafe extern "C" fn(i32) -> u8 = seam_low_unsigned;
            let _: unsafe extern "C" fn(i8, u8, i16, u16, bool) -> i32 = seam_widen;
        };
    };
}
#[allow(unused_imports)]
pub(crate) use assert_implementations;
