; Generated by svmgen for LLVM 23. ABI: d3342f8e738d98009b02ac606e6d283a15b96646bbf41ad6a5bcd0a9c2c13d9e
; Apply these contracts to actual objects using svmgen apply before ThinLTO indexing.
source_filename = "seam-contracts"
target triple = "aarch64-apple-darwin"

declare i64 @seam_inspect(ptr align 8 dereferenceable(8) captures(none) nonnull readonly %value) nounwind willreturn
declare i64 @seam_sum(ptr %isolate_thread, ptr nonnull %data, i64 %length) nounwind

!svmgen.contract = !{!0}
!0 = !{!"d3342f8e738d98009b02ac606e6d283a15b96646bbf41ad6a5bcd0a9c2c13d9e"}
