; Generated by svmgen for LLVM 23. ABI: 48366837bdd46637037cf534922cd7ac9da7a519a97994acb36a0a2fc36e4d21
; Apply these contracts to actual objects using svmgen apply before ThinLTO indexing.
source_filename = "seam-contracts"
target triple = "aarch64-apple-darwin"

declare i64 @seam_inspect(ptr align 8 dereferenceable(8) captures(none) nonnull readonly %value) nounwind willreturn
declare i64 @seam_sum(ptr %isolate_thread, ptr nonnull %data, i64 %length) nounwind

!svmgen.contract = !{!0}
!0 = !{!"48366837bdd46637037cf534922cd7ac9da7a519a97994acb36a0a2fc36e4d21"}
