// Generated by svmgen. Raw ABI; callers uphold ownership and contracts.
pub const ABI_FINGERPRINT: &str = "d3342f8e738d98009b02ac606e6d283a15b96646bbf41ad6a5bcd0a9c2c13d9e";
const _: () = assert!(core::mem::size_of::<*const ()>() == 8);
#[repr(C)]
pub struct Buffer { _private: [u8; 0] }
#[repr(C)]
pub struct BufferView {
    pub data: *mut u8,
    pub length: u64,
    pub flags: u32,
    pub seamPadding0: [u8; 4],
}
const _: () = {
    assert!(core::mem::size_of::<BufferView>() == 24);
    assert!(core::mem::align_of::<BufferView>() == 8);
    assert!(core::mem::offset_of!(BufferView, data) == 0);
    assert!(core::mem::offset_of!(BufferView, length) == 8);
    assert!(core::mem::offset_of!(BufferView, flags) == 16);
};

unsafe extern "C" {
    // IMPORT; error=NO_FAILURE
    // value: nullable=false ownership=BORROWED access=READ
    #[link_name = "seam_inspect"]
    pub fn inspect(value: *const i64) -> i64;
    // EXPORT; error=INTEGER_SENTINEL
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // data: nullable=false ownership=BORROWED access=READ
    // length: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_sum"]
    pub fn sum(isolate_thread: *mut core::ffi::c_void, data: *const u8, length: i64) -> i64;
}

/// Pins each import's implementation, in scope under its symbol name, to this ABI.
#[allow(unused_macros)]
macro_rules! assert_implementations {
    () => {
        const _: () = {
            let _: unsafe extern "C" fn(*const i64) -> i64 = seam_inspect;
        };
    };
}
#[allow(unused_imports)]
pub(crate) use assert_implementations;
