// Generated by svmgen. Enable only in Native Image applications using the FFM bindings.
package dev.elide.seam.generated;

import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeClassInitialization;
import org.graalvm.nativeimage.hosted.RuntimeForeignAccess;

public final class SeamForeignFeature implements Feature {
    @Override public void duringSetup(DuringSetupAccess access) {
        RuntimeForeignAccess.registerForDowncall(SeamFFM.classify_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$classify_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.echo_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$echo_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.exercise_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$exercise_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.forEach_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$forEach_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.inspect_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$inspect_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.isHigh_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$isHigh_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.lowSigned_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$lowSigned_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.lowUnsigned_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$lowUnsigned_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.reducer_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$reducer_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.rotate_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$rotate_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.scale_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$scale_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.spread_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$spread_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.structProbe_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$structProbe_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.sum_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$sum_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.swapPair_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$swapPair_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.visit_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$visit_Binding");
        RuntimeForeignAccess.registerForDowncall(SeamFFM.widen_DESCRIPTOR);
        RuntimeClassInitialization.initializeAtRunTime("dev.elide.seam.generated.SeamFFM$widen_Binding");
    }
}
