/* Generated by svmgen. ABI: 48366837bdd46637037cf534922cd7ac9da7a519a97994acb36a0a2fc36e4d21 */
#ifndef BUFFER_SEAM_H
#define BUFFER_SEAM_H
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
#define SEAM_ASSERT static_assert
#define SEAM_ALIGNOF alignof
extern "C" {
#else
#define SEAM_ASSERT _Static_assert
#define SEAM_ALIGNOF _Alignof
#endif

#define BUFFER_SEAM_ABI "48366837bdd46637037cf534922cd7ac9da7a519a97994acb36a0a2fc36e4d21"
SEAM_ASSERT(sizeof(void *) == 8, "seam target requires 64-bit pointers");

struct Buffer;
struct BufferView {
  uint8_t * data;
  uint64_t length;
  uint32_t flags;
  uint8_t seamPadding0[4];
};
SEAM_ASSERT(sizeof(struct BufferView) == 24, "struct size");
SEAM_ASSERT(SEAM_ALIGNOF(struct BufferView) == 8, "struct alignment");
SEAM_ASSERT(offsetof(struct BufferView, data) == 0, "field offset");
SEAM_ASSERT(offsetof(struct BufferView, length) == 8, "field offset");
SEAM_ASSERT(offsetof(struct BufferView, flags) == 16, "field offset");

/* IMPORT; error=NO_FAILURE */
/* value: nullable=false ownership=BORROWED access=READ */
int64_t seam_inspect(int64_t const * value);

/* EXPORT; error=INTEGER_SENTINEL */
/* isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED */
/* data: nullable=false ownership=BORROWED access=READ */
/* length: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
int64_t seam_sum(void * isolate_thread, uint8_t const * data, int64_t length);

#ifdef __cplusplus
}
#endif
#undef SEAM_ASSERT
#undef SEAM_ALIGNOF
#endif
