// Generated by svmgen; Java 25 FFM.
package dev.elide.seam.generated;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;

public final class SeamFFM {
    private SeamFFM() {}
    public static final String ABI_FINGERPRINT = "833c9c4355813400466776e8c0b7e51f3203b0dc81a41f22631a671aa5695dfc";
    static {
        if (ValueLayout.ADDRESS.byteSize() != 8) throw new ExceptionInInitializerError("64-bit seam target required");
    }
    public static final StructLayout BufferView_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.ADDRESS.withName("data"),
        ValueLayout.JAVA_LONG.withName("length"),
        ValueLayout.JAVA_INT.withName("flags"),
        MemoryLayout.paddingLayout(4));
    public static final long BufferView_data_OFFSET = 0L;
    public static final long BufferView_length_OFFSET = 8L;
    public static final long BufferView_flags_OFFSET = 16L;
    public static final StructLayout Pair_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_LONG.withName("left"),
        ValueLayout.JAVA_INT.withName("right"),
        MemoryLayout.paddingLayout(4));
    public static final long Pair_left_OFFSET = 0L;
    public static final long Pair_right_OFFSET = 8L;
    public static final StructLayout Triple_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_LONG.withName("a"),
        ValueLayout.JAVA_LONG.withName("b"),
        ValueLayout.JAVA_LONG.withName("c"));
    public static final long Triple_a_OFFSET = 0L;
    public static final long Triple_b_OFFSET = 8L;
    public static final long Triple_c_OFFSET = 16L;
    public static final FunctionDescriptor classify_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_BYTE, ValueLayout.ADDRESS, ValueLayout.JAVA_SHORT, ValueLayout.JAVA_BOOLEAN);
    public static MethodHandle classify(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_classify").orElseThrow(() -> new UnsatisfiedLinkError("seam_classify")), classify_DESCRIPTOR);
    }
    public static final FunctionDescriptor echo_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_BYTE, ValueLayout.ADDRESS, ValueLayout.JAVA_BYTE);
    public static MethodHandle echo(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_echo").orElseThrow(() -> new UnsatisfiedLinkError("seam_echo")), echo_DESCRIPTOR);
    }
    public static final FunctionDescriptor exercise_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS);
    public static MethodHandle exercise(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_exercise").orElseThrow(() -> new UnsatisfiedLinkError("seam_exercise")), exercise_DESCRIPTOR);
    }
    public static final FunctionDescriptor forEach_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG);
    public static MethodHandle forEach(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_for_each").orElseThrow(() -> new UnsatisfiedLinkError("seam_for_each")), forEach_DESCRIPTOR);
    }
    public static final FunctionDescriptor inspect_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS);
    public static MethodHandle inspect(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_inspect").orElseThrow(() -> new UnsatisfiedLinkError("seam_inspect")), inspect_DESCRIPTOR);
    }
    public static final FunctionDescriptor isHigh_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_BYTE);
    public static MethodHandle isHigh(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_is_high").orElseThrow(() -> new UnsatisfiedLinkError("seam_is_high")), isHigh_DESCRIPTOR);
    }
    public static final FunctionDescriptor lowSigned_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_BYTE, ValueLayout.JAVA_INT);
    public static MethodHandle lowSigned(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_low_signed").orElseThrow(() -> new UnsatisfiedLinkError("seam_low_signed")), lowSigned_DESCRIPTOR);
    }
    public static final FunctionDescriptor lowUnsigned_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_BYTE, ValueLayout.JAVA_INT);
    public static MethodHandle lowUnsigned(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_low_unsigned").orElseThrow(() -> new UnsatisfiedLinkError("seam_low_unsigned")), lowUnsigned_DESCRIPTOR);
    }
    public static final FunctionDescriptor reducer_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.ADDRESS);
    public static MethodHandle reducer(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_reducer").orElseThrow(() -> new UnsatisfiedLinkError("seam_reducer")), reducer_DESCRIPTOR);
    }
    public static final FunctionDescriptor rotate_DESCRIPTOR = FunctionDescriptor.of(Triple_LAYOUT, Triple_LAYOUT, ValueLayout.JAVA_INT);
    public static MethodHandle rotate(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_rotate").orElseThrow(() -> new UnsatisfiedLinkError("seam_rotate")), rotate_DESCRIPTOR);
    }
    public static final FunctionDescriptor scale_DESCRIPTOR = FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS);
    public static MethodHandle scale(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_scale_svmgen_ref").orElseThrow(() -> new UnsatisfiedLinkError("seam_scale_svmgen_ref")), scale_DESCRIPTOR);
    }
    public static final FunctionDescriptor spread_DESCRIPTOR = FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS);
    public static MethodHandle spread(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_spread_svmgen_ref").orElseThrow(() -> new UnsatisfiedLinkError("seam_spread_svmgen_ref")), spread_DESCRIPTOR);
    }
    public static final FunctionDescriptor structProbe_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS);
    public static MethodHandle structProbe(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_struct_probe").orElseThrow(() -> new UnsatisfiedLinkError("seam_struct_probe")), structProbe_DESCRIPTOR);
    }
    public static final FunctionDescriptor sum_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG);
    public static MethodHandle sum(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_sum").orElseThrow(() -> new UnsatisfiedLinkError("seam_sum")), sum_DESCRIPTOR);
    }
    public static final FunctionDescriptor swapPair_DESCRIPTOR = FunctionDescriptor.of(Pair_LAYOUT, Pair_LAYOUT);
    public static MethodHandle swapPair(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_swap_pair").orElseThrow(() -> new UnsatisfiedLinkError("seam_swap_pair")), swapPair_DESCRIPTOR);
    }
    public static final FunctionDescriptor visit_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG);
    public static MethodHandle visit(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_visit").orElseThrow(() -> new UnsatisfiedLinkError("seam_visit")), visit_DESCRIPTOR);
    }
    public static final FunctionDescriptor widen_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_BYTE, ValueLayout.JAVA_BYTE, ValueLayout.JAVA_SHORT, ValueLayout.JAVA_SHORT, ValueLayout.JAVA_BOOLEAN);
    public static MethodHandle widen(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_widen").orElseThrow(() -> new UnsatisfiedLinkError("seam_widen")), widen_DESCRIPTOR);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class classify_Binding {
        static final MethodHandle HANDLE = SeamFFM.classify(SymbolLookup.loaderLookup());
    }
    public static byte classify(MemorySegment isolate_thread, short value, boolean strict) throws Throwable {
        return (byte) SeamFFM.classify_Binding.HANDLE.invokeExact(isolate_thread, value, strict);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class echo_Binding {
        static final MethodHandle HANDLE = SeamFFM.echo(SymbolLookup.loaderLookup());
    }
    public static byte echo(MemorySegment isolate_thread, byte value) throws Throwable {
        return (byte) SeamFFM.echo_Binding.HANDLE.invokeExact(isolate_thread, value);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class exercise_Binding {
        static final MethodHandle HANDLE = SeamFFM.exercise(SymbolLookup.loaderLookup());
    }
    public static long exercise(MemorySegment isolate_thread) throws Throwable {
        return (long) SeamFFM.exercise_Binding.HANDLE.invokeExact(isolate_thread);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class forEach_Binding {
        static final MethodHandle HANDLE = SeamFFM.forEach(SymbolLookup.loaderLookup());
    }
    public static int forEach(MemorySegment visitor, MemorySegment isolate, long count) throws Throwable {
        return (int) SeamFFM.forEach_Binding.HANDLE.invokeExact(visitor, isolate, count);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class inspect_Binding {
        static final MethodHandle HANDLE = SeamFFM.inspect(SymbolLookup.loaderLookup());
    }
    public static long inspect(MemorySegment value) throws Throwable {
        return (long) SeamFFM.inspect_Binding.HANDLE.invokeExact(value);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class isHigh_Binding {
        static final MethodHandle HANDLE = SeamFFM.isHigh(SymbolLookup.loaderLookup());
    }
    public static boolean isHigh(MemorySegment isolate_thread, byte value) throws Throwable {
        return (boolean) SeamFFM.isHigh_Binding.HANDLE.invokeExact(isolate_thread, value);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class lowSigned_Binding {
        static final MethodHandle HANDLE = SeamFFM.lowSigned(SymbolLookup.loaderLookup());
    }
    public static byte lowSigned(int value) throws Throwable {
        return (byte) SeamFFM.lowSigned_Binding.HANDLE.invokeExact(value);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class lowUnsigned_Binding {
        static final MethodHandle HANDLE = SeamFFM.lowUnsigned(SymbolLookup.loaderLookup());
    }
    public static byte lowUnsigned(int value) throws Throwable {
        return (byte) SeamFFM.lowUnsigned_Binding.HANDLE.invokeExact(value);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class reducer_Binding {
        static final MethodHandle HANDLE = SeamFFM.reducer(SymbolLookup.loaderLookup());
    }
    public static MemorySegment reducer() throws Throwable {
        return (MemorySegment) SeamFFM.reducer_Binding.HANDLE.invokeExact();
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class rotate_Binding {
        static final MethodHandle HANDLE = SeamFFM.rotate(SymbolLookup.loaderLookup());
    }
    public static MemorySegment rotate(SegmentAllocator allocator, MemorySegment value, int times) throws Throwable {
        return (MemorySegment) SeamFFM.rotate_Binding.HANDLE.invokeExact(allocator, value, times);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class scale_Binding {
        static final MethodHandle HANDLE = SeamFFM.scale(SymbolLookup.loaderLookup());
    }
    public static void scale(MemorySegment isolate_thread, MemorySegment value, int factor, MemorySegment result) throws Throwable {
        SeamFFM.scale_Binding.HANDLE.invokeExact(isolate_thread, value, factor, result);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class spread_Binding {
        static final MethodHandle HANDLE = SeamFFM.spread(SymbolLookup.loaderLookup());
    }
    public static void spread(MemorySegment isolate_thread, MemorySegment value, MemorySegment result) throws Throwable {
        SeamFFM.spread_Binding.HANDLE.invokeExact(isolate_thread, value, result);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class structProbe_Binding {
        static final MethodHandle HANDLE = SeamFFM.structProbe(SymbolLookup.loaderLookup());
    }
    public static int structProbe(MemorySegment isolate_thread) throws Throwable {
        return (int) SeamFFM.structProbe_Binding.HANDLE.invokeExact(isolate_thread);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class sum_Binding {
        static final MethodHandle HANDLE = SeamFFM.sum(SymbolLookup.loaderLookup());
    }
    public static long sum(MemorySegment isolate_thread, MemorySegment data, long length) throws Throwable {
        return (long) SeamFFM.sum_Binding.HANDLE.invokeExact(isolate_thread, data, length);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class swapPair_Binding {
        static final MethodHandle HANDLE = SeamFFM.swapPair(SymbolLookup.loaderLookup());
    }
    public static MemorySegment swapPair(SegmentAllocator allocator, MemorySegment value) throws Throwable {
        return (MemorySegment) SeamFFM.swapPair_Binding.HANDLE.invokeExact(allocator, value);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class visit_Binding {
        static final MethodHandle HANDLE = SeamFFM.visit(SymbolLookup.loaderLookup());
    }
    public static int visit(MemorySegment isolate_thread, long value) throws Throwable {
        return (int) SeamFFM.visit_Binding.HANDLE.invokeExact(isolate_thread, value);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class widen_Binding {
        static final MethodHandle HANDLE = SeamFFM.widen(SymbolLookup.loaderLookup());
    }
    public static int widen(byte signedByte, byte unsignedByte, short signedShort, short unsignedShort, boolean flag) throws Throwable {
        return (int) SeamFFM.widen_Binding.HANDLE.invokeExact(signedByte, unsignedByte, signedShort, unsignedShort, flag);
    }
}
