/* Generated by svmgen. ABI: 7662bb31a02f7f7b753df3d135114daa4c9102b5355d7629f02a1e332d408706 */
#ifndef BUFFER_SEAM_H
#define BUFFER_SEAM_H
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
#define SEAM_ASSERT static_assert
#define SEAM_ALIGNOF alignof
extern "C" {
#else
#define SEAM_ASSERT _Static_assert
#define SEAM_ALIGNOF _Alignof
#endif

#define BUFFER_SEAM_ABI "7662bb31a02f7f7b753df3d135114daa4c9102b5355d7629f02a1e332d408706"
SEAM_ASSERT(sizeof(void *) == 8, "seam target requires 64-bit pointers");

struct Buffer;
struct BufferView;
typedef int64_t (*Reducer)(int64_t left, int64_t right);
typedef int32_t (*Visitor)(void * isolate, int64_t value);
struct BufferView {
  uint8_t * data;
  uint64_t length;
  uint32_t flags;
  uint8_t seamPadding0[4];
};
SEAM_ASSERT(sizeof(struct BufferView) == 24, "struct size");
SEAM_ASSERT(SEAM_ALIGNOF(struct BufferView) == 8, "struct alignment");
SEAM_ASSERT(offsetof(struct BufferView, data) == 0, "field offset");
SEAM_ASSERT(offsetof(struct BufferView, length) == 8, "field offset");
SEAM_ASSERT(offsetof(struct BufferView, flags) == 16, "field offset");

/* EXPORT; error=ABORT */
/* isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED */
/* value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
/* strict: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
int8_t seam_classify(void * isolate_thread, int16_t value, bool strict);

/* EXPORT; error=ABORT */
/* isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED */
/* value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
uint8_t seam_echo(void * isolate_thread, uint8_t value);

/* EXPORT; error=ABORT */
/* isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED */
int64_t seam_exercise(void * isolate_thread);

/* IMPORT; error=NO_FAILURE */
/* visitor: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
/* isolate: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
/* count: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
int32_t seam_for_each(Visitor visitor, void * isolate, int64_t count);

/* IMPORT; error=NO_FAILURE */
/* value: nullable=false ownership=BORROWED access=READ */
int64_t seam_inspect(int64_t const * value);

/* EXPORT; error=ABORT */
/* isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED */
/* value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
bool seam_is_high(void * isolate_thread, uint8_t value);

/* IMPORT; error=NO_FAILURE */
/* value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
int8_t seam_low_signed(int32_t value);

/* IMPORT; error=NO_FAILURE */
/* value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
uint8_t seam_low_unsigned(int32_t value);

/* IMPORT; error=NO_FAILURE */
Reducer seam_reducer(void);

/* EXPORT; error=INTEGER_SENTINEL */
/* isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED */
/* data: nullable=false ownership=BORROWED access=READ */
/* length: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
int64_t seam_sum(void * isolate_thread, uint8_t const * data, int64_t length);

/* EXPORT; error=ABORT */
/* isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED */
/* value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
int32_t seam_visit(void * isolate_thread, int64_t value);

/* IMPORT; error=NO_FAILURE */
/* signedByte: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
/* unsignedByte: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
/* signedShort: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
/* unsignedShort: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
/* flag: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED */
int32_t seam_widen(int8_t signedByte, uint8_t unsignedByte, int16_t signedShort, uint16_t unsignedShort, bool flag);

#ifdef __cplusplus
}
#endif
#undef SEAM_ASSERT
#undef SEAM_ALIGNOF
#endif
