; Generated by myna for LLVM 23. ABI: d44ec22d7c3a435496ea647adde107ba12093ac69cc1cb1fb165a07ff5292436
; Apply these contracts to actual objects using myna apply before ThinLTO indexing.
source_filename = "seam-contracts"
target triple = "aarch64-apple-darwin"

declare i8 @seam_classify(ptr %isolate_thread, i16 signext %value, i1 zeroext %strict)
declare i8 @seam_echo(ptr %isolate_thread, i8 zeroext %value)
declare i64 @seam_exercise(ptr %isolate_thread)
declare i32 @seam_for_each(ptr %visitor, ptr %isolate, i64 %count)
declare i64 @seam_inspect(ptr align 8 dereferenceable(8) captures(none) nonnull readonly %value) nounwind willreturn
declare i1 @seam_is_high(ptr %isolate_thread, i8 zeroext %value)
declare i8 @seam_low_signed(i32 %value) nounwind willreturn
declare i8 @seam_low_unsigned(i32 %value) nounwind willreturn
declare ptr @seam_reducer()
declare void @seam_rotate_myna_ref(ptr align 8 dereferenceable(24) captures(none) nonnull readonly %value, i32 %times, ptr align 8 dereferenceable(24) captures(none) nonnull writeonly %result) nounwind
declare void @seam_scale_myna_ref(ptr %isolate_thread, ptr align 8 dereferenceable(16) captures(none) nonnull readonly %value, i32 %factor, ptr align 8 dereferenceable(16) captures(none) nonnull writeonly %result)
declare void @seam_spread_myna_ref(ptr %isolate_thread, ptr align 8 dereferenceable(24) captures(none) nonnull readonly %value, ptr align 8 dereferenceable(24) captures(none) nonnull writeonly %result)
declare i32 @seam_struct_probe(ptr %isolate_thread)
declare i64 @seam_sum(ptr %isolate_thread, ptr nonnull %data, i64 %length) nounwind
declare void @seam_swap_pair_myna_ref(ptr align 8 dereferenceable(16) captures(none) nonnull readonly %value, ptr align 8 dereferenceable(16) captures(none) nonnull writeonly %result) nounwind
declare i32 @seam_visit(ptr %isolate_thread, i64 %value)
declare i32 @seam_widen(i8 signext %signedByte, i8 zeroext %unsignedByte, i16 signext %signedShort, i16 zeroext %unsignedShort, i1 zeroext %flag) nounwind willreturn

!myna.contract = !{!0}
!0 = !{!"d44ec22d7c3a435496ea647adde107ba12093ac69cc1cb1fb165a07ff5292436"}
