// Generated by myna. Raw ABI; callers uphold ownership and contracts.
pub const ABI_FINGERPRINT: &str = "d44ec22d7c3a435496ea647adde107ba12093ac69cc1cb1fb165a07ff5292436";
const _: () = assert!(core::mem::size_of::<*const ()>() == 8);
#[repr(C)]
pub struct Buffer { _private: [u8; 0] }
pub type Reducer = Option<unsafe extern "C" fn(i64, i64) -> i64>;
pub type Visitor = Option<unsafe extern "C" fn(*mut core::ffi::c_void, i64) -> i32>;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct BufferView {
    pub data: *mut u8,
    pub length: u64,
    pub flags: u32,
    pub seamPadding0: [u8; 4],
}
const _: () = {
    assert!(core::mem::size_of::<BufferView>() == 24);
    assert!(core::mem::align_of::<BufferView>() == 8);
    assert!(core::mem::offset_of!(BufferView, data) == 0);
    assert!(core::mem::offset_of!(BufferView, length) == 8);
    assert!(core::mem::offset_of!(BufferView, flags) == 16);
};
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Pair {
    pub left: i64,
    pub right: i32,
    pub seamPadding0: [u8; 4],
}
const _: () = {
    assert!(core::mem::size_of::<Pair>() == 16);
    assert!(core::mem::align_of::<Pair>() == 8);
    assert!(core::mem::offset_of!(Pair, left) == 0);
    assert!(core::mem::offset_of!(Pair, right) == 8);
};
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Triple {
    pub a: i64,
    pub b: i64,
    pub c: i64,
}
const _: () = {
    assert!(core::mem::size_of::<Triple>() == 24);
    assert!(core::mem::align_of::<Triple>() == 8);
    assert!(core::mem::offset_of!(Triple, a) == 0);
    assert!(core::mem::offset_of!(Triple, b) == 8);
    assert!(core::mem::offset_of!(Triple, c) == 16);
};

unsafe extern "C" {
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // strict: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_classify"]
    pub fn classify(isolate_thread: *mut core::ffi::c_void, value: i16, strict: bool) -> i8;
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_echo"]
    pub fn echo(isolate_thread: *mut core::ffi::c_void, value: u8) -> u8;
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    #[link_name = "seam_exercise"]
    pub fn exercise(isolate_thread: *mut core::ffi::c_void) -> i64;
    // IMPORT; error=NO_FAILURE
    // visitor: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // isolate: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // count: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_for_each"]
    pub fn forEach(visitor: Visitor, isolate: *mut core::ffi::c_void, count: i64) -> i32;
    // IMPORT; error=NO_FAILURE
    // value: nullable=false ownership=BORROWED access=READ
    #[link_name = "seam_inspect"]
    pub fn inspect(value: *const i64) -> i64;
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_is_high"]
    pub fn isHigh(isolate_thread: *mut core::ffi::c_void, value: u8) -> bool;
    // IMPORT; error=NO_FAILURE
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_low_signed"]
    pub fn lowSigned(value: i32) -> i8;
    // IMPORT; error=NO_FAILURE
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_low_unsigned"]
    pub fn lowUnsigned(value: i32) -> u8;
    // IMPORT; error=NO_FAILURE
    #[link_name = "seam_reducer"]
    pub fn reducer() -> Reducer;
    // IMPORT; error=NO_FAILURE
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // times: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_rotate"]
    pub fn rotate(value: Triple, times: i32) -> Triple;
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=false ownership=BORROWED access=READ
    // factor: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // result: nullable=false ownership=BORROWED access=WRITE
    #[link_name = "seam_scale_myna_ref"]
    pub fn scaleRef(isolate_thread: *mut core::ffi::c_void, value: *const Pair, factor: i32, result: *mut Pair);
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=false ownership=BORROWED access=READ
    // result: nullable=false ownership=BORROWED access=WRITE
    #[link_name = "seam_spread_myna_ref"]
    pub fn spreadRef(isolate_thread: *mut core::ffi::c_void, value: *const Triple, result: *mut Triple);
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    #[link_name = "seam_struct_probe"]
    pub fn structProbe(isolate_thread: *mut core::ffi::c_void) -> i32;
    // EXPORT; error=INTEGER_SENTINEL
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // data: nullable=false ownership=BORROWED access=READ
    // length: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_sum"]
    pub fn sum(isolate_thread: *mut core::ffi::c_void, data: *const u8, length: i64) -> i64;
    // IMPORT; error=NO_FAILURE
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_swap_pair"]
    pub fn swapPair(value: Pair) -> Pair;
    // EXPORT; error=ABORT
    // isolate_thread: nullable=false ownership=BORROWED access=UNSPECIFIED
    // value: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_visit"]
    pub fn visit(isolate_thread: *mut core::ffi::c_void, value: i64) -> i32;
    // IMPORT; error=NO_FAILURE
    // signedByte: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // unsignedByte: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // signedShort: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // unsignedShort: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    // flag: nullable=true ownership=UNSPECIFIED access=UNSPECIFIED
    #[link_name = "seam_widen"]
    pub fn widen(signedByte: i8, unsignedByte: u8, signedShort: i16, unsignedShort: u16, flag: bool) -> i32;
}
#[inline]
#[allow(non_snake_case, clippy::missing_safety_doc)]
pub unsafe fn scale(isolate_thread: *mut core::ffi::c_void, value: Pair, factor: i32) -> Pair {
    let mut result = core::mem::MaybeUninit::<Pair>::uninit();
    unsafe { scaleRef(isolate_thread, &value, factor, result.as_mut_ptr()) };
    unsafe { result.assume_init() }
}
#[inline]
#[allow(non_snake_case, clippy::missing_safety_doc)]
pub unsafe fn spread(isolate_thread: *mut core::ffi::c_void, value: Triple) -> Triple {
    let mut result = core::mem::MaybeUninit::<Triple>::uninit();
    unsafe { spreadRef(isolate_thread, &value, result.as_mut_ptr()) };
    unsafe { result.assume_init() }
}
pub type ClassifyFn = unsafe extern "C" fn(*mut core::ffi::c_void, i16, bool) -> i8;
pub type EchoFn = unsafe extern "C" fn(*mut core::ffi::c_void, u8) -> u8;
pub type ExerciseFn = unsafe extern "C" fn(*mut core::ffi::c_void) -> i64;
pub type ForEachFn = unsafe extern "C" fn(Visitor, *mut core::ffi::c_void, i64) -> i32;
pub type InspectFn = unsafe extern "C" fn(*const i64) -> i64;
pub type IsHighFn = unsafe extern "C" fn(*mut core::ffi::c_void, u8) -> bool;
pub type LowSignedFn = unsafe extern "C" fn(i32) -> i8;
pub type LowUnsignedFn = unsafe extern "C" fn(i32) -> u8;
pub type ReducerFn = unsafe extern "C" fn() -> Reducer;
pub type RotateFn = unsafe extern "C" fn(Triple, i32) -> Triple;
pub type ScaleFn = unsafe extern "C" fn(*mut core::ffi::c_void, *const Pair, i32, *mut Pair);
pub type SpreadFn = unsafe extern "C" fn(*mut core::ffi::c_void, *const Triple, *mut Triple);
pub type StructProbeFn = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
pub type SumFn = unsafe extern "C" fn(*mut core::ffi::c_void, *const u8, i64) -> i64;
pub type SwapPairFn = unsafe extern "C" fn(Pair) -> Pair;
pub type VisitFn = unsafe extern "C" fn(*mut core::ffi::c_void, i64) -> i32;
pub type WidenFn = unsafe extern "C" fn(i8, u8, i16, u16, bool) -> i32;

/// Pins each import's implementation, in scope under its symbol name, to this ABI.
/// Pass this module's path when the declared types are not in scope.
#[allow(unused_macros)]
macro_rules! assert_implementations {
    () => {
        const _: () = {
            let _: unsafe extern "C" fn(Visitor, *mut core::ffi::c_void, i64) -> i32 = seam_for_each;
            let _: unsafe extern "C" fn(*const i64) -> i64 = seam_inspect;
            let _: unsafe extern "C" fn(i32) -> i8 = seam_low_signed;
            let _: unsafe extern "C" fn(i32) -> u8 = seam_low_unsigned;
            let _: unsafe extern "C" fn() -> Reducer = seam_reducer;
            let _: unsafe extern "C" fn(Triple, i32) -> Triple = seam_rotate;
            let _: unsafe extern "C" fn(Pair) -> Pair = seam_swap_pair;
            let _: unsafe extern "C" fn(i8, u8, i16, u16, bool) -> i32 = seam_widen;
        };
    };
    ($($seam:ident)::+) => {
        const _: () = {
            let _: unsafe extern "C" fn($($seam)::+::Visitor, *mut core::ffi::c_void, i64) -> i32 = seam_for_each;
            let _: unsafe extern "C" fn(*const i64) -> i64 = seam_inspect;
            let _: unsafe extern "C" fn(i32) -> i8 = seam_low_signed;
            let _: unsafe extern "C" fn(i32) -> u8 = seam_low_unsigned;
            let _: unsafe extern "C" fn() -> $($seam)::+::Reducer = seam_reducer;
            let _: unsafe extern "C" fn($($seam)::+::Triple, i32) -> $($seam)::+::Triple = seam_rotate;
            let _: unsafe extern "C" fn($($seam)::+::Pair) -> $($seam)::+::Pair = seam_swap_pair;
            let _: unsafe extern "C" fn(i8, u8, i16, u16, bool) -> i32 = seam_widen;
        };
    };
}
#[allow(unused_imports)]
pub(crate) use assert_implementations;

/// Defines the Native Image reference forms of by-value imports beside their
/// implementations; pass this module's path.
#[allow(unused_macros)]
macro_rules! native_image_shims {
    ($($seam:ident)::+) => {
        #[unsafe(no_mangle)]
        #[allow(non_snake_case)]
        pub unsafe extern "C" fn seam_rotate_myna_ref(value: *const $($seam)::+::Triple, times: i32, result: *mut $($seam)::+::Triple) {
            unsafe { result.write(seam_rotate(value.read(), times)) }
        }
        #[unsafe(no_mangle)]
        #[allow(non_snake_case)]
        pub unsafe extern "C" fn seam_swap_pair_myna_ref(value: *const $($seam)::+::Pair, result: *mut $($seam)::+::Pair) {
            unsafe { result.write(seam_swap_pair(value.read())) }
        }
    };
}
#[allow(unused_imports)]
pub(crate) use native_image_shims;
