// Generated by svmgen; Java 25 FFM.
package dev.elide.seam.generated;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;

public final class SeamFFM {
    private SeamFFM() {}
    public static final String ABI_FINGERPRINT = "d3342f8e738d98009b02ac606e6d283a15b96646bbf41ad6a5bcd0a9c2c13d9e";
    static {
        if (ValueLayout.ADDRESS.byteSize() != 8) throw new ExceptionInInitializerError("64-bit seam target required");
    }
    public static final StructLayout BufferView_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.ADDRESS.withName("data"),
        ValueLayout.JAVA_LONG.withName("length"),
        ValueLayout.JAVA_INT.withName("flags"),
        MemoryLayout.paddingLayout(4));
    public static final long BufferView_data_OFFSET = 0L;
    public static final long BufferView_length_OFFSET = 8L;
    public static final long BufferView_flags_OFFSET = 16L;
    public static final FunctionDescriptor inspect_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS);
    public static MethodHandle inspect(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_inspect").orElseThrow(() -> new UnsatisfiedLinkError("seam_inspect")), inspect_DESCRIPTOR);
    }
    public static final FunctionDescriptor sum_DESCRIPTOR = FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG);
    public static MethodHandle sum(SymbolLookup lookup) {
        return Linker.nativeLinker().downcallHandle(lookup.find("seam_sum").orElseThrow(() -> new UnsatisfiedLinkError("seam_sum")), sum_DESCRIPTOR);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class inspect_Binding {
        static final MethodHandle HANDLE = SeamFFM.inspect(SymbolLookup.loaderLookup());
    }
    public static long inspect(MemorySegment value) throws Throwable {
        return (long) SeamFFM.inspect_Binding.HANDLE.invokeExact(value);
    }
    // Load the library in this class loader before first use. One handle per symbol.
    private static final class sum_Binding {
        static final MethodHandle HANDLE = SeamFFM.sum(SymbolLookup.loaderLookup());
    }
    public static long sum(MemorySegment isolate_thread, MemorySegment data, long length) throws Throwable {
        return (long) SeamFFM.sum_Binding.HANDLE.invokeExact(isolate_thread, data, length);
    }
}
